const oracledb = require('./server/node_modules/oracledb');
const path = require('path');
const dotenv = require('./server/node_modules/dotenv');

// Load environment variables
dotenv.config({ path: path.join(__dirname, 'server', '.env') });

async function run() {
    let connection;
    try {
        oracledb.initOracleClient({ libDir: path.join(__dirname, 'server', 'instantclient_19_19') });

        const dbConfig = {
            user: process.env.DB_USER,
            password: process.env.DB_PASSWORD,
            connectString: `${process.env.DB_HOST}:${process.env.DB_PORT}/${process.env.DB_SERVICE_NAME}`
        };

        connection = await oracledb.getConnection(dbConfig);

        const scripts = [
            `DROP TABLE MSAI_SITE_ASSIGNMENTS`,
            `CREATE TABLE MSAI_SITE_ASSIGNMENTS (
                IMPORT_ACTION VARCHAR2(100),
                BATCH_ID VARCHAR2(255),
                LEGACY_VENDOR_NAME VARCHAR2(720) NOT NULL,
                VENDOR_NUMBER VARCHAR2(90),
                LEGACY_VENDOR_SITE_CODE VARCHAR2(240) NOT NULL,
                PROCUREMENT_BUSINESS_UNIT_NAME VARCHAR2(720) NOT NULL,
                BUSINESS_UNIT_NAME VARCHAR2(720) NOT NULL,
                BILL_TO_BU_NAME VARCHAR2(720),
                LEGACY_SHIP_TO_LOCATION_CODE VARCHAR2(180),
                LEGACY_BILL_TO_LOCATION_CODE VARCHAR2(180),
                ALLOW_AWT_FLAG VARCHAR2(3),
                AWT_GROUP_NAME VARCHAR2(75),
                ACCTS_PAY_CONCAT_SEGMENTS VARCHAR2(465),
                PREPAY_CONCAT_SEGMENTS VARCHAR2(465),
                FUTURE_DATED_CONCAT_SEGMENTS VARCHAR2(465),
                DISTRIBUTION_SET_NAME VARCHAR2(255),
                INACTIVE_DATE VARCHAR2(20),
                VENDOR_SITE_ID NUMBER,
                VENDOR_ID NUMBER,
                BUSINESS_UNIT VARCHAR2(240),
                LEGISLATIVE_DATA_GROUP VARCHAR2(240),
                COUNTRY VARCHAR2(240),
                ORG_NAME VARCHAR2(360),
                SEGMENT1 VARCHAR2(1000),
                SEGMENT2 VARCHAR2(1000),
                SEGMENT3 VARCHAR2(1000),
                SEGMENT4 VARCHAR2(1000),
                SEGMENT5 VARCHAR2(1000),
                SEGMENT6 VARCHAR2(1000),
                SEGMENT7 VARCHAR2(1000),
                PREPAY_CONCAT_SEGMENT1 VARCHAR2(100),
                PREPAY_CONCAT_SEGMENT2 VARCHAR2(100),
                PREPAY_CONCAT_SEGMENT3 VARCHAR2(100),
                PREPAY_CONCAT_SEGMENT4 VARCHAR2(100),
                PREPAY_CONCAT_SEGMENT5 VARCHAR2(100),
                PREPAY_CONCAT_SEGMENT6 VARCHAR2(100),
                PREPAY_CONCAT_SEGMENT7 VARCHAR2(100),
                PREPAY_CONCAT_SEGMENT8 VARCHAR2(100),
                PREPAY_CONCAT_SEGMENT9 VARCHAR2(100),
                PREPAY_CONCAT_SEGMENT10 VARCHAR2(100),
                RECORD_TYPE VARCHAR2(50),
                LAST_MERGED_BY NUMBER,
                LAST_MERGED_NAME VARCHAR2(100),
                LAST_MERGED_DATE DATE,
                CREATED_BY NUMBER,
                CREATED_NAME VARCHAR2(100),
                CREATION_DATE DATE,
                LAST_UPDATED_BY NUMBER,
                LAST_UPDATED_NAME VARCHAR2(100),
                LAST_UPDATE_DATE DATE,
                TARGET_VENDOR_NAME VARCHAR2(720),
                TARGET_VENDOR_SITE_CODE VARCHAR2(240),
                TARGET_SHIP_TO_LOCATION_CODE VARCHAR2(180),
                TARGET_BILL_TO_LOCATION_CODE VARCHAR2(180),
                LAST_UPDATE_LOGIN NUMBER,
                CONSTRAINT PK_MSAI_SITE_ASSIGNMENTS PRIMARY KEY (LEGACY_VENDOR_NAME, LEGACY_VENDOR_SITE_CODE, PROCUREMENT_BUSINESS_UNIT_NAME, BUSINESS_UNIT_NAME)
            )`,

            `DROP TABLE MSAI_SUPPLIER_ADDRESSES`,
            `CREATE TABLE MSAI_SUPPLIER_ADDRESSES (
                LEGACY_VENDOR_NAME VARCHAR2(720) NOT NULL,
                LEGACY_PARTY_SITE_NAME VARCHAR2(720) NOT NULL,
                PARTY_SITE_NAME_NEW VARCHAR2(255),
                ADDRESS_COUNTRY VARCHAR2(180),
                ADDRESS_LINE1 VARCHAR2(720) NOT NULL,
                ADDRESS_LINE2 VARCHAR2(720),
                ADDRESS_LINE3 VARCHAR2(720),
                ADDRESS_LINE4 VARCHAR2(720),
                ADDRESS_LINES_PHONETIC VARCHAR2(1680),
                BUILDING VARCHAR2(150),
                FLOOR_NUMBER VARCHAR2(150),
                CITY VARCHAR2(180),
                STATE VARCHAR2(180),
                PROVINCE VARCHAR2(180),
                COUNTY VARCHAR2(180),
                POSTAL_CODE VARCHAR2(180) NOT NULL,
                POSTAL_PLUS4_CODE VARCHAR2(30),
                ADDRESSEE VARCHAR2(1080),
                GLOBAL_LOCATION_NUMBER VARCHAR2(255),
                PARTY_SITE_LANGUAGE VARCHAR2(90),
                INACTIVE_DATE VARCHAR2(20),
                PHONE_COUNTRY_CODE VARCHAR2(30),
                PHONE_AREA_CODE VARCHAR2(30),
                PHONE VARCHAR2(120),
                PHONE_EXTENSION VARCHAR2(60),
                FAX_COUNTRY_CODE VARCHAR2(30),
                FAX_AREA_CODE VARCHAR2(30),
                FAX VARCHAR2(120),
                RFQ_OR_BIDDING_PURPOSE_FLAG VARCHAR2(1),
                ORDERING_PURPOSE_FLAG VARCHAR2(1),
                REMIT_TO_PURPOSE_FLAG VARCHAR2(1),
                EMAIL_ADDRESS VARCHAR2(6000),
                DELIVERY_CHANNEL_CODE VARCHAR2(255),
                BANK_INSTRUCTION1_CODE VARCHAR2(255),
                BANK_INSTRUCTION2_CODE VARCHAR2(255),
                BANK_INSTRUCTION_DETAILS VARCHAR2(255),
                SETTLEMENT_PRIORITY VARCHAR2(255),
                PAYMENT_TEXT_MESSAGE1 VARCHAR2(255),
                PAYMENT_TEXT_MESSAGE2 VARCHAR2(255),
                PAYMENT_TEXT_MESSAGE3 VARCHAR2(255),
                SERVICE_LEVEL_CODE VARCHAR2(255),
                EXCLUSIVE_PAYMENT_FLAG VARCHAR2(255),
                IBY_BANK_CHARGE_BEARER VARCHAR2(255),
                PAYMENT_REASON_CODE VARCHAR2(255),
                PAYMENT_REASON_COMMENTS VARCHAR2(255),
                REMIT_ADV_DELIVERY_METHOD VARCHAR2(255),
                REMIT_ADVICE_EMAIL VARCHAR2(255),
                REMIT_ADVICE_FAX VARCHAR2(255),
                PARTY_SITE_ID NUMBER,
                VENDOR_ID NUMBER,
                IMPORT_ACTION VARCHAR2(10),
                BATCH_ID VARCHAR2(200),
                REMIT_ADVICE_DELIVERY_METHOD VARCHAR2(30),
                BUSINESS_UNIT VARCHAR2(240),
                LEGISLATIVE_DATA_GROUP VARCHAR2(240),
                COUNTRY VARCHAR2(240),
                TARGET_PARTY_SITE_NAME VARCHAR2(240),
                TARGET_PARTY_SITE_NUMBER VARCHAR2(240),
                RECORD_TYPE VARCHAR2(50),
                LAST_MERGED_BY NUMBER,
                LAST_MERGED_NAME VARCHAR2(100),
                LAST_MERGED_DATE DATE,
                CREATED_BY NUMBER,
                CREATED_NAME VARCHAR2(100),
                CREATION_DATE DATE,
                LAST_UPDATED_BY NUMBER,
                LAST_UPDATED_NAME VARCHAR2(100),
                LAST_UPDATE_DATE DATE,
                TARGET_VENDOR_NAME VARCHAR2(720),
                LEGACY_PARTY_SITE_NUMBER VARCHAR2(240),
                LAST_UPDATE_LOGIN NUMBER,
                CONSTRAINT PK_MSAI_SUPPLIER_ADDRESSES PRIMARY KEY (LEGACY_VENDOR_NAME, LEGACY_PARTY_SITE_NAME)
            )`,

            `DROP TABLE MSAI_SUPPLIER_CONTACTS`,
            `CREATE TABLE MSAI_SUPPLIER_CONTACTS (
                BATCH_ID VARCHAR2(100),
                IMPORT_ACTION VARCHAR2(10),
                LEGACY_VENDOR_NAME VARCHAR2(200) NOT NULL,
                VENDOR_ID NUMBER,
                PARTY_SITE_ID NUMBER,
                VENDOR_SITE_CODE VARCHAR2(200) NOT NULL,
                PREFIX VARCHAR2(360),
                FIRST_NAME VARCHAR2(150) NOT NULL,
                FIRST_NAME_NEW VARCHAR2(150),
                MIDDLE_NAME VARCHAR2(150),
                LAST_NAME VARCHAR2(150) NOT NULL,
                LAST_NAME_NEW VARCHAR2(150),
                JOB_TITLE VARCHAR2(100),
                ADMINISTRATIVE_CONTACT VARCHAR2(1),
                E_MAIL VARCHAR2(320),
                E_MAIL_NEW VARCHAR2(320),
                PHONE_COUNTRY_CODE VARCHAR2(10),
                PHONE_AREA_CODE VARCHAR2(10),
                PHONE VARCHAR2(40),
                PHONE_EXTENSION VARCHAR2(20),
                FAX_COUNTRY_CODE VARCHAR2(10),
                FAX_AREA_CODE VARCHAR2(10),
                FAX VARCHAR2(40),
                MOBILE_COUNTRY_CODE VARCHAR2(10),
                MOBILE_AREA_CODE VARCHAR2(10),
                MOBILE VARCHAR2(40),
                INACTIVE_DATE DATE,
                USER_ACCOUNT_ACTION VARCHAR2(100),
                ROLE_1 VARCHAR2(4000),
                ROLE_2 VARCHAR2(4000),
                ROLE_3 VARCHAR2(4000),
                ROLE_4 VARCHAR2(4000),
                ROLE_5 VARCHAR2(4000),
                ROLE_6 VARCHAR2(4000),
                ROLE_7 VARCHAR2(4000),
                ROLE_8 VARCHAR2(4000),
                ROLE_9 VARCHAR2(4000),
                ROLE_10 VARCHAR2(4000),
                VAL_VENDOR_SITE_ID NUMBER,
                VAL_VENDOR_ID NUMBER,
                VAL_PARTY_SITE_ID NUMBER,
                VAL_PER_PARTY_ID NUMBER,
                RELATIONSHIP_ID NUMBER,
                REL_PARTY_ID NUMBER,
                ORG_CONTACT_ID NUMBER,
                ORG_PARTY_SITE_ID NUMBER,
                BUSINESS_UNIT VARCHAR2(240),
                LEGISLATIVE_DATA_GROUP VARCHAR2(240),
                COUNTRY VARCHAR2(240),
                RECORD_TYPE VARCHAR2(50),
                LAST_MERGED_BY NUMBER,
                LAST_MERGED_NAME VARCHAR2(100),
                LAST_MERGED_DATE DATE,
                CREATED_BY NUMBER,
                CREATED_NAME VARCHAR2(100),
                CREATION_DATE DATE,
                LAST_UPDATED_BY NUMBER,
                LAST_UPDATED_NAME VARCHAR2(100),
                LAST_UPDATE_DATE DATE,
                LAST_UPDATE_LOGIN NUMBER,
                CONSTRAINT PK_MSAI_SUPPLIER_CONTACTS PRIMARY KEY (LEGACY_VENDOR_NAME, VENDOR_SITE_CODE, FIRST_NAME, LAST_NAME)
            )`,

            `DROP TABLE MSAI_SUPPLIER_HEADERS`,
            `CREATE TABLE MSAI_SUPPLIER_HEADERS (
                LEGACY_VENDOR_NAME VARCHAR2(720) NOT NULL,
                VENDOR_NAME_NEW VARCHAR2(255),
                LEGACY_SEGMENT1 VARCHAR2(90),
                VENDOR_NAME_ALT VARCHAR2(960),
                ORGANIZATION_TYPE_LOOKUP_CODE VARCHAR2(75) NOT NULL,
                VENDOR_TYPE_LOOKUP_CODE VARCHAR2(90) NOT NULL,
                END_DATE_ACTIVE VARCHAR2(20),
                BUSINESS_RELATIONSHIP VARCHAR2(255) NOT NULL,
                PARENT_SUPPLIER_NAME VARCHAR2(255),
                ALIAS VARCHAR2(720),
                DUNS_NUMBER NUMBER,
                ONE_TIME_FLAG VARCHAR2(3),
                CUSTOMER_NUM VARCHAR2(75),
                STANDARD_INDUSTRY_CLASS VARCHAR2(75),
                NI_NUMBER VARCHAR2(90),
                CORPORATE_WEBSITE VARCHAR2(255),
                CHIEF_EXECUTIVE_TITLE VARCHAR2(255),
                CHIEF_EXECUTIVE_NAME VARCHAR2(255),
                BC_NOT_APPLICABLE_FLAG VARCHAR2(255),
                TAX_COUNTRY_CODE VARCHAR2(255),
                NUM_1099 VARCHAR2(90),
                FEDERAL_REPORTABLE_FLAG VARCHAR2(3),
                TYPE_1099 VARCHAR2(30),
                STATE_REPORTABLE_FLAG VARCHAR2(3),
                TAX_REPORTING_NAME VARCHAR2(240),
                NAME_CONTROL VARCHAR2(12),
                TAX_VERIFICATION_DATE DATE,
                ALLOW_AWT_FLAG VARCHAR2(3),
                AWT_GROUP_NAME VARCHAR2(75),
                VAT_CODE VARCHAR2(90),
                VAT_REGISTRATION_NUM VARCHAR2(60),
                AUTO_TAX_CALC_OVERRIDE VARCHAR2(3),
                PAYMENT_METHOD_LOOKUP_CODE VARCHAR2(75),
                DELIVERY_CHANNEL_CODE VARCHAR2(90),
                BANK_INSTRUCTION1_CODE VARCHAR2(90),
                BANK_INSTRUCTION2_CODE VARCHAR2(90),
                BANK_INSTRUCTION_DETAILS VARCHAR2(765),
                SETTLEMENT_PRIORITY VARCHAR2(90),
                PAYMENT_TEXT_MESSAGE1 VARCHAR2(768),
                PAYMENT_TEXT_MESSAGE2 VARCHAR2(450),
                PAYMENT_TEXT_MESSAGE3 VARCHAR2(450),
                IBY_BANK_CHARGE_BEARER VARCHAR2(90),
                PAYMENT_REASON_CODE VARCHAR2(90),
                PAYMENT_REASON_COMMENTS VARCHAR2(720),
                PAYMENT_FORMAT_CODE VARCHAR2(90),
                PARTY_NUMBER VARCHAR2(90),
                SERVICE_LEVEL_CODE VARCHAR2(90),
                EXCLUSIVE_PAYMENT_FLAG VARCHAR2(3),
                REMIT_ADVICE_DELIVERY_METHOD VARCHAR2(90),
                REMIT_ADVICE_EMAIL VARCHAR2(765),
                REMIT_ADVICE_FAX VARCHAR2(300),
                DATAFOX_COMPANY_ID VARCHAR2(255),
                VENDOR_ID NUMBER,
                IMPORT_ACTION VARCHAR2(10),
                TARGET_VENDOR_NAME VARCHAR2(360),
                TARGET_SEGMENT1 VARCHAR2(30),
                LEGISLATIVE_DATA_GROUP VARCHAR2(240),
                COUNTRY VARCHAR2(240),
                LEGACY_VENDOR_TYPE_LOOKUP_CODE VARCHAR2(360) NOT NULL,
                BATCH_ID VARCHAR2(200),
                BUSINESS_UNIT VARCHAR2(240),
                RECORD_TYPE VARCHAR2(50),
                LAST_MERGED_BY NUMBER,
                LAST_MERGED_NAME VARCHAR2(100),
                LAST_MERGED_DATE DATE,
                CREATED_BY NUMBER,
                CREATED_NAME VARCHAR2(100),
                CREATION_DATE DATE,
                LAST_UPDATED_BY NUMBER,
                LAST_UPDATED_NAME VARCHAR2(100),
                LAST_UPDATE_DATE DATE,
                LAST_UPDATE_LOGIN NUMBER,
                CONSTRAINT PK_MSAI_SUPPLIER_HEADERS PRIMARY KEY (LEGACY_VENDOR_NAME)
            )`,

            `DROP TABLE MSAI_SUPPLIER_SITES`,
            `CREATE TABLE MSAI_SUPPLIER_SITES (
                LEGACY_VENDOR_NAME VARCHAR2(720) NOT NULL,
                PROCUREMENT_BUSINESS_UNIT_NAME VARCHAR2(720) NOT NULL,
                LEGACY_PARTY_SITE_NAME VARCHAR2(720),
                LEGACY_VENDOR_SITE_CODE VARCHAR2(240) NOT NULL,
                VENDOR_SITE_CODE_NEW VARCHAR2(255),
                INACTIVE_DATE VARCHAR2(20),
                RFQ_ONLY_SITE_FLAG VARCHAR2(3),
                PURCHASING_SITE_FLAG VARCHAR2(3) NOT NULL,
                PCARD_SITE_FLAG VARCHAR2(3),
                PAY_SITE_FLAG VARCHAR2(3),
                PRIMARY_PAY_SITE_FLAG VARCHAR2(3),
                TAX_REPORTING_SITE_FLAG VARCHAR2(3),
                VENDOR_SITE_CODE_ALT VARCHAR2(960),
                CUSTOMER_NUM VARCHAR2(75),
                B2B_COMM_METHOD_CODE VARCHAR2(255),
                B2B_SITE_CODE VARCHAR2(255),
                SUPPLIER_NOTIF_METHOD VARCHAR2(75),
                EMAIL_ADDRESS VARCHAR2(6000),
                FAX_COUNTRY_CODE VARCHAR2(255),
                FAX_AREA_CODE VARCHAR2(30),
                FAX VARCHAR2(45),
                HOLD_FLAG VARCHAR2(3),
                PURCHASING_HOLD_REASON VARCHAR2(720),
                CARRIER VARCHAR2(75),
                MODE_OF_TRANSPORT_CODE VARCHAR2(255),
                SERVICE_LEVEL_CODE VARCHAR2(90),
                FREIGHT_TERMS_LOOKUP_CODE VARCHAR2(75),
                PAY_ON_CODE VARCHAR2(75),
                FOB_LOOKUP_CODE VARCHAR2(75),
                COUNTRY_OF_ORIGIN_CODE VARCHAR2(6),
                BUYER_MANAGED_TRANSPORT_FLAG VARCHAR2(255),
                PAY_ON_USE_FLAG VARCHAR2(255),
                AGING_ONSET_POINT VARCHAR2(255),
                AGING_PERIOD_DAYS VARCHAR2(255),
                CONSUMPTION_ADVICE_FREQUENCY VARCHAR2(255),
                CONSUMPTION_ADVICE_SUMMARY VARCHAR2(255),
                DEFAULT_PAY_SITE_CODE VARCHAR2(3),
                PAY_ON_RECEIPT_SUMMARY_CODE VARCHAR2(255),
                GAPLESS_INV_NUM_FLAG VARCHAR2(3),
                SELLING_COMPANY_IDENTIFIER VARCHAR2(30),
                CREATE_DEBIT_MEMO_FLAG VARCHAR2(75),
                ENFORCE_SHIP_TO_LOCATION_CODE VARCHAR2(75),
                RECEIVING_ROUTING_ID NUMBER,
                QTY_RCV_TOLERANCE NUMBER,
                QTY_RCV_EXCEPTION_CODE VARCHAR2(75),
                DAYS_EARLY_RECEIPT_ALLOWED NUMBER,
                DAYS_LATE_RECEIPT_ALLOWED NUMBER,
                ALLOW_SUBSTITUTE_RECEIPTS_FLAG VARCHAR2(3),
                ALLOW_UNORDERED_RECEIPTS_FLAG VARCHAR2(3),
                RECEIPT_DAYS_EXCEPTION_CODE VARCHAR2(75),
                INVOICE_CURRENCY_CODE VARCHAR2(45),
                INVOICE_AMOUNT_LIMIT NUMBER,
                MATCH_OPTION VARCHAR2(75),
                MATCH_APPROVAL_LEVEL VARCHAR2(255),
                PAYMENT_CURRENCY_CODE VARCHAR2(45),
                PAYMENT_PRIORITY NUMBER,
                PAY_GROUP_LOOKUP_CODE VARCHAR2(75),
                TOLERANCE_NAME VARCHAR2(255),
                SERVICES_TOLERANCE VARCHAR2(255),
                HOLD_ALL_PAYMENTS_FLAG VARCHAR2(3),
                HOLD_UNMATCHED_INVOICES_FLAG VARCHAR2(3),
                HOLD_FUTURE_PAYMENTS_FLAG VARCHAR2(3),
                HOLD_BY NUMBER,
                PAYMENT_HOLD_DATE VARCHAR2(20),
                HOLD_REASON VARCHAR2(720),
                TERMS_NAME VARCHAR2(150),
                TERMS_DATE_BASIS VARCHAR2(75),
                PAY_DATE_BASIS_LOOKUP_CODE VARCHAR2(75),
                BANK_CHARGE_DEDUCTION_TYPE VARCHAR2(255),
                ALWAYS_TAKE_DISC_FLAG VARCHAR2(3),
                EXCLUDE_FREIGHT_FROM_DISCOUNT VARCHAR2(3),
                EXCLUDE_TAX_FROM_DISCOUNT VARCHAR2(255),
                AUTO_CALCULATE_INTEREST_FLAG VARCHAR2(3),
                VAT_CODE VARCHAR2(90),
                VAT_REGISTRATION_NUM VARCHAR2(60),
                PAY_METHOD_LOOKUP_CODE VARCHAR2(75),
                DELIVERY_CHANNEL_CODE VARCHAR2(90),
                BANK_INSTRUCTION1_CODE VARCHAR2(90),
                BANK_INSTRUCTION2_CODE VARCHAR2(90),
                BANK_INSTRUCTION_DETAILS VARCHAR2(765),
                SETTLEMENT_PRIORITY VARCHAR2(90),
                PAYMENT_TEXT_MESSAGE1 VARCHAR2(768),
                PAYMENT_TEXT_MESSAGE2 VARCHAR2(450),
                PAYMENT_TEXT_MESSAGE3 VARCHAR2(450),
                IBY_BANK_CHARGE_BEARER VARCHAR2(90),
                PAYMENT_REASON_CODE VARCHAR2(90),
                PAYMENT_REASON_COMMENTS VARCHAR2(720),
                REMIT_ADVICE_DELIVERY_METHOD VARCHAR2(90),
                REMITTANCE_EMAIL VARCHAR2(765),
                REMITTANCE_FAX VARCHAR2(32767),
                PO_ACK_REQD_CODE VARCHAR2(255),
                PO_ACK_REQD_DAYS VARCHAR2(255),
                INVOICE_CHANNEL VARCHAR2(255),
                PAYEE_SERVICE_LEVEL_CODE VARCHAR2(255),
                EXCLUSIVE_PAYMENT_FLAG VARCHAR2(3),
                VENDOR_SITE_ID NUMBER,
                PARTY_SITE_ID NUMBER,
                VENDOR_ID NUMBER,
                PAYMENT_METHOD_LOOKUP_CODE VARCHAR2(75),
                IMPORT_ACTION VARCHAR2(10),
                BATCH_ID VARCHAR2(200),
                BUSINESS_UNIT VARCHAR2(240),
                LEGISLATIVE_DATA_GROUP VARCHAR2(240),
                COUNTRY VARCHAR2(240),
                ORG_NAME VARCHAR2(150),
                TARGET_VENDOR_SITE_CODE VARCHAR2(240),
                TARGET_VENDOR_NAME VARCHAR2(360),
                RECORD_TYPE VARCHAR2(50),
                LAST_MERGED_BY NUMBER,
                LAST_MERGED_NAME VARCHAR2(100),
                LAST_MERGED_DATE DATE,
                CREATED_BY NUMBER,
                CREATED_NAME VARCHAR2(100),
                CREATION_DATE DATE,
                LAST_UPDATED_BY NUMBER,
                LAST_UPDATED_NAME VARCHAR2(100),
                LAST_UPDATE_DATE DATE,
                TARGET_PARTY_SITE_NAME VARCHAR2(720),
                LAST_UPDATE_LOGIN NUMBER,
                CONSTRAINT PK_MSAI_SUPPLIER_SITES PRIMARY KEY (LEGACY_VENDOR_NAME, LEGACY_VENDOR_SITE_CODE, PROCUREMENT_BUSINESS_UNIT_NAME)
            )`
        ];

        for (const sql of scripts) {
            try {
                if (sql.startsWith('DROP')) {
                    console.log(`Executing: ${sql}`);
                    try {
                        await connection.execute(sql);
                    } catch (e) { console.log('ignored drop error'); }
                } else {
                    console.log(`Executing CREATE Table...`);
                    await connection.execute(sql);
                    console.log('Success.');
                }
            } catch (err) {
                console.error('Error executing SQL:', err);
            }
        }

    } catch (err) {
        console.error(err);
    } finally {
        if (connection) {
            try {
                await connection.close();
            } catch (err) {
                console.error(err);
            }
        }
    }
}

run();
